server:
  port: 8080

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: gateway-service

  cloud:
    gateway:
      routes:
        - id: user-service
          uri : lb://USER-SERVICE
          predicates:
            - Path=/user/api/**
          filters:
            - CustomAuthFilter
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user/auth/**
        - id: community-service
          uri: lb://COMMUNITY-SERVICE
          predicates:
            - Path=/community/**

jwt:
  secret: c3ByaW5nLWJvb3Qtc2VjdXJpdHktand0LXR1dG9yaWFsLWppd29vbi1zcHJpbmctYm9vdC1zZWN1cml0eS1qd3QtdHV0b3JpYWwK