server:
  port: 64412

spring:
  application:
    name: user-service

eureka:
  instance:
    instance-id: user-microservice-instatnce

  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaluZone: http://localhost:8761/eureka