server:
  port: 54412

spring:
  application:
    name: order-service

eureka:
  instance:
    instance-id: order-microservice-instatnce

  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaluZone: http://localhost:8761/eureka