server:
  port: 8888

spring:
  application:
    name: config-service

  cloud:
    config:
      server:
        git:
          uri: https://github.com/whipbaek/msa-configurations
          skip-ssl-validation: true
